/* Generated by CMake -- see CMakeLists.txt. Mirrors the autotools config.h. */
#ifndef FDKAAC_CONFIG_H
#define FDKAAC_CONFIG_H

/*
 * These flags gate "if HAVE_X" / "elif HAVE_X" preprocessor checks in the
 * source, which need the macro to always be present with a 0/1 value.
 */
#cmakedefine01 WORDS_BIGENDIAN
#cmakedefine01 HAVE_STDINT_H
#cmakedefine01 HAVE_INTTYPES_H
#cmakedefine01 HAVE_UNISTD_H
#cmakedefine01 HAVE_ENDIAN_H
#cmakedefine01 HAVE_BYTESWAP_H
#cmakedefine01 HAVE_LIBCHARSET_H
#cmakedefine01 HAVE_LANGINFO_H
#cmakedefine01 HAVE_SIGACTION
#cmakedefine01 HAVE_FSEEKO64
#cmakedefine01 HAVE_STRUCT___TIMEB64

/*
 * These flags gate "ifndef X" / "defined(X)" checks, so they must only be
 * present at all when true (present-but-0 would still count as defined).
 */
#cmakedefine HAVE_ICONV
#cmakedefine HAVE_FSEEKO
#cmakedefine HAVE__VSCPRINTF
#cmakedefine HAVE_GETOPT_LONG

#endif /* FDKAAC_CONFIG_H */
